{
  "formatVersion": "1.1",
  "component": {
    "group": "linktrail.io",
    "module": "sdk",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.1.aar",
          "url": "sdk-0.0.1.aar",
          "size": 141573,
          "sha512": "87e93ff54849fd648c12ebc365a46c7077117683a90c2e922747e0c07743fb43fe627498220ee24536e9cc640372d2f09eb3a5903a0dead53c04afded05905f4",
          "sha256": "672b4b8986b15c5f1afc04f593b19fd0710a565641abbea292d694732d2b5a77",
          "sha1": "15dd170164f0093546334b57579dc31515a1ebc7",
          "md5": "d6c2fe4eaf3aa6b852e9255b7a8687d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.1.aar",
          "url": "sdk-0.0.1.aar",
          "size": 141573,
          "sha512": "87e93ff54849fd648c12ebc365a46c7077117683a90c2e922747e0c07743fb43fe627498220ee24536e9cc640372d2f09eb3a5903a0dead53c04afded05905f4",
          "sha256": "672b4b8986b15c5f1afc04f593b19fd0710a565641abbea292d694732d2b5a77",
          "sha1": "15dd170164f0093546334b57579dc31515a1ebc7",
          "md5": "d6c2fe4eaf3aa6b852e9255b7a8687d0"
        }
      ]
    }
  ]
}