{
  "formatVersion": "1.1",
  "component": {
    "group": "linktrail.io",
    "module": "sdk",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.3.aar",
          "url": "sdk-0.0.3.aar",
          "size": 142378,
          "sha512": "bf9dc5ec53b15932cc236ed299fe4bf323b9e3d350ff1258b84b3f860667c8699e998e424ea53348ff5a4b1c31ec400d2f694348d112e5530e7500fb7378ac2e",
          "sha256": "a3576e444a0c44203af63402fd726f82403bce99a077be3f36d5d0f718748ef8",
          "sha1": "8618e7efc660da7b7940aaf7c8b00c6818fab179",
          "md5": "04523c12f6480634d327a781e8099137"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.3.aar",
          "url": "sdk-0.0.3.aar",
          "size": 142378,
          "sha512": "bf9dc5ec53b15932cc236ed299fe4bf323b9e3d350ff1258b84b3f860667c8699e998e424ea53348ff5a4b1c31ec400d2f694348d112e5530e7500fb7378ac2e",
          "sha256": "a3576e444a0c44203af63402fd726f82403bce99a077be3f36d5d0f718748ef8",
          "sha1": "8618e7efc660da7b7940aaf7c8b00c6818fab179",
          "md5": "04523c12f6480634d327a781e8099137"
        }
      ]
    }
  ]
}