{
  "formatVersion": "1.1",
  "component": {
    "group": "linktrail.io",
    "module": "sdk",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.2.aar",
          "url": "sdk-0.0.2.aar",
          "size": 142721,
          "sha512": "c1478739f18e7c13c10deb3d64cd7067e2e1721ba533e9612ba430dfeedb26fcf05ddfe4c20c5f9df78cfd7db012782de9083acb5d0ea43d916b4ca354954ab8",
          "sha256": "7276d01d8a5500759512de78ff355c362e863d18041c55a6373eafc16cb492fa",
          "sha1": "21c6a355f83cf2c50366a86b9c3f24c983e259f2",
          "md5": "28e09d3bb07ce75ab59482f6889e98d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.0.2.aar",
          "url": "sdk-0.0.2.aar",
          "size": 142721,
          "sha512": "c1478739f18e7c13c10deb3d64cd7067e2e1721ba533e9612ba430dfeedb26fcf05ddfe4c20c5f9df78cfd7db012782de9083acb5d0ea43d916b4ca354954ab8",
          "sha256": "7276d01d8a5500759512de78ff355c362e863d18041c55a6373eafc16cb492fa",
          "sha1": "21c6a355f83cf2c50366a86b9c3f24c983e259f2",
          "md5": "28e09d3bb07ce75ab59482f6889e98d5"
        }
      ]
    }
  ]
}